# Generated by Django 3.2.7 on 2021-09-26 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_remove_choiceset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choiceset',
            name='choice_num',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(2)]),
        ),
    ]
