# Generated by Django 3.2.7 on 2021-09-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_auto_20210926_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceset',
            name='create_date',
            field=models.DateField(auto_now=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='choiceset',
            name='update_date',
            field=models.DateField(auto_now_add=True, verbose_name='date updated'),
        ),
    ]
