# Generated by Django 3.2.7 on 2021-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0004_auto_20210926_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choiceset_id',
            field=models.IntegerField(default=0),
        ),
    ]
