# Generated by Django 3.2.7 on 2021-10-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0005_choice_choiceset_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choiceset_id',
        ),
    ]
